const actions = {
  SET_STATE: "trainingexercises/SET_STATE",
  TRAININGEXERCISES_LIST: "trainingexercises/LIST",
  TRAININGEXERCISES_CATEGORIES: "trainingexercises/CATEGORIES",
  TRAININGEXERCISES_CATEGORIES_DETAIL: "trainingexercises/CATEGORIES_DETAIL",
  REMOVE_CATEGORY: "trainingexercises/REMOVE_CATEGORY",
  REMOVE_CATEGORY_SUCCESS: "trainingexercises/REMOVE_CATEGORY_SUCCESS",
  TRAININGEXERCISES_CATEGORIE: "trainingexercises/CATEGORIE",
  TRAININGEXERCISES_MY_CATEGORIE: "trainingexercises/MY_CATEGORIE",
  TRAININGEXERCISES_MY_CATEGORI: "trainingexercises/MY_CATEGORI",
  TRAININGEXERCISES_CREATE_CATEGORY: "trainingexercises/CREATE_CATEGORY",
  TRAININGEXERCISES_EDIT_CATEGORY: "trainingexercises/EDIT_CATEGORY",
  TRAININGEXERCISES_CREATE_EXERCISE: "trainingexercises/CREATE_EXERCISE",
  REMOVE_EXERCISE: "trainingexercises/REMOVE_EXERCISE",
  LIST_MY_TRAINING: "trainingexercises/LIST_MY_TRAINING",
  TRAININGEXERCISES_PHILOSOPHY: "trainingexercises/PHILOSOPHY",
  TRAININGEXERCISES_SET_DEFAULT: "trainingexercises/TRAININGEXERCISES_SET_DEFAULT",
};

export default actions;
