const actions = {
  SET_STATE: "userInfo/SET_STATE",
  GET_INFO_ABOUT_SESSION: "userInfo/GET_INFO_ABOUT_SESSION",
  CURRENT_EXERCISES: "userInfo/CURRENT_EXERCISES",
  POST_QUESTIONNAIRE: "userInfo/POST_QUESTIONNAIRE",
  POST_MATCH_QUESTIONNAIRE: "userInfo/MATCH_QUESTIONNAIRE",
  ADD_PLAYER_MATCH_DYNAMIC_ANSWERS: "userInfo/ADD_PLAYER_MATCH_DYNAMIC_ANSWERS",
};

export default actions;
