const actions = {
  SET_STATE: 'home/SET_STATE',
  HOME_LIST: 'home/LIST',
  MANAGER_LIST: 'home/MANAGER_LIST',
  LIST_CALENDAR: 'home/LIST_CALENDAR',
  LIST_NEXT_ACTIVES: 'home/LIST_NEXT_ACTIVES',
  LIST_MATCHES_ACTIVES: 'home/LIST_MATCHES_ACTIVES',
  USER_LIST_CALENDAR: 'user/USER_LIST_CALENDAR',
  SET_CALENDAR: 'user/SET_CALENDAR',
  GET_CALENDAR_EVENTS: 'user/GET_CALENDAR_EVENTS',
  GET_TRAINING_BUILDUP_TYPES: 'user/GET_TRAINING_BUILDUP_TYPES',
};

export default actions;
