const actions = {
  SET_STATE: 'match/SET_STATE',
  UPDATE_MATCH: 'match/UPDATE_MATCH',
  UPDATE_MATCH_SQUAD: 'match/UPDATE_MATCH_SQUAD',
  UPDATE_MATCH_SUMMARY: 'match/UPDATE_MATCH_SUMMARY',
  UPDATE_MATCH_PLAYERS: 'match/UPDATE_MATCH_PLAYERS',
  SET_MATCH_STATIC_STATE: 'match/SET_MATCH_STATIC_STATE',
  UPDATE_MATCH_STATIC_DATA: 'match/UPDATE_MATCH_STATIC_DATA',
  UPDATE_MATCH_DYNAMIC_DATA: 'match/UPDATE_MATCH_DYNAMIC_DATA',
  UPDATE_MATCH_REPORT_EDITED: 'match/UPDATE_MATCH_REPORT_EDITED',
  UPDATE_MATCH_PLAYERS_POSITIONS: 'match/UPDATE_MATCH_PLAYERS_POSITIONS',
};

export default actions;
