const actions = {
  SET_INTERNAL_STATE: 'blog/SET_INTERNAL_STATE',
  SET_STATE: 'blog/SET_STATE',
  BLOG_LIST: 'blog/LIST',
  BLOG_DETAILS: 'blog/DETAILS',
  BLOG_GET_CATEGORY: 'blog/BLOG_GET_CATEGORY',
  BLOG_GET_CATEGORIES: 'blog/BLOG_GET_CATEGORIES',
  BLOG_CREATE_CATEGORY: 'blog/BLOG_CREATE_CATEGORY',
  BLOG_GET_BLOG: 'blog/BLOG_GET_BLOG',
  BLOG_CREATE_BLOG: 'blog/BLOG_CREATE_BLOG',
};

export default actions;
