const actions = {
    SET_STATE: 'managersettings/SET_STATE',
    GET_MANAGER_SCOUTS: 'managersettings/GET_MANAGER_SCOUTS',
    GET_MANAGER_DOMAINS: 'managersettings/GET_MANAGER_DOMAINS',
    GET_MANAGER_COACHES: 'managersettings/GET_MANAGER_COACHES',
    GET_MANAGER_AGEGROUPS: 'managersettings/GET_MANAGER_AGEGROUPS',
    GET_MANAGER_TRAININGS: 'managersettings/GET_MANAGER_TRAININGS',
    GET_MANAGER_SUBMANAGERS: 'managersettings/GET_MANAGER_SUBMANAGERS',
    GET_MANAGER_REPORTS_BULK: 'managersettings/GET_MANAGER_REPORTS_BULK',
    GET_MATCH_DYNAMIC_FIELDS: 'managersettings/GET_MATCH_DYNAMIC_FIELDS',
    SAVE_MATCH_DYNAMIC_FIELDS: 'managersettings/SAVE_MATCH_DYNAMIC_FIELDS',
    GET_MANAGER_TRAININGTYPES: 'managersettings/GET_MANAGER_TRAINING_TYPES',
    GET_MANAGER_SCOUTREPORTS_BULK: 'managersettings/GET_MANAGER_SCOUTREPORTS_BULK',
    GET_MANAGER_MATCH_QUESTIONNAIRE: 'managersettings/GET_MANAGER_MATCH_QUESTIONNAIRE',
  };
  
  export default actions;
  