const actions = {
  SET_STATE: 'user/SET_STATE',
  LOGIN: 'user/LOGIN',
  SIGN_IN: 'user/SIGN_IN',
  REGISTER: 'user/REGISTER',
  LOAD_CURRENT_ACCOUNT: 'user/LOAD_CURRENT_ACCOUNT',
  LOGOUT: 'user/LOGOUT',
  FORGOT_PASSWORD: 'user/FORGOT_PASSWORD',
  RESET_PASSWORD: 'user/RESET_PASSWORD',
  UPDATE_PROFILE: 'user/UPDATE_PROFILE',
  CHANGE_PASSWORD: 'user/CHANGE_PASSWORD',
  GET_AGE_GROUPS: 'user/GET_AGE_GROUPS',
  DEFAULT_PROFILE: 'user/DEFAULT_PROFILE',
  RECOVER_ACCOUNT: 'user/RECOVER_ACCOUNT',
  DEFAULT_RECOVER_ACCOUNT: 'user/DEFAULT_RECOVER_ACCOUNT',
};

export default actions;
